config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

from tinia_manager.tinia import views

urlpatterns = [
    # path("", views.index, name="index"),
    path(
        "",
        views.IndexPageView.as_view(template_name="pages/bulletin_texts.html"),
        name="bulletin_texts",
    ),
    path("home", views.home, name="homedata"),
    path("translation", views.translation, name="translation"),
    path(
        "create/texts",
        views.BulletinCreate.as_view(template_name="pages/bulletinview.html"),
        name="bulletin_create",
    ),
    path(
        "update/complete",
        views.bulletinTextUpdate,
        name="bulletin_update_complete",
    ),
    path(
        "delete/<str:pk>",
        views.bulletinDelete,
        name="bulletin_delete",
    ),
    path(
        "view/<str:pk>",
        views.BulletinDetailView.as_view(template_name="pages/bulletinview.html"),
        name="bulletin_view",
    ),
    path("send/", views.sendView, name="send"),
    path(
        "bulletindata/",
        views.BulletinDataDetail.as_view(template_name="pages/bulletin_data.html"),
        name="bulletin_data",
    ),
    path(
        "bulletinpseudoradar/",
        views.PseudoRadarBulletinPageView.as_view(),
        name="bulletin_pseudoradar",
    ),
    path(
        "dashboard/",
        views.DashboardPageView.as_view(template_name="pages/dashboard.html"),
        name="dashboard",
    ),
    path(
        "user_regions/",
        views.ManageRegion.as_view(template_name="pages/user_region.html"),
        name="user_region",
    ),
    path(
        "user_region/<int:id>",
        views.RegionSelect.as_view(template_name="pages/region_select.html"),
        name="region_select",
    ),
    path("user_region_save", views.userRegionSave, name="user_region_save"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    path("cms/", views.CmsPageView.as_view(), name="cms"),
    path(
        "cms/config.yml",
        TemplateView.as_view(template_name="pages/config.yml", content_type="text/yaml"),
        name="cms-config",
    ),
    path("gitlab.com/<path:path>", views.GitlabProxyView.as_view(), name="gitlab"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("tinia_manager.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # https://django-invitations.readthedocs.io/en/latest/installation.html#requirements
    path("invitations/", include("invitations.urls", namespace="invitations")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # API webhooks
    path("api/webhooks/forecasts/", views.forecasts_webhook, name="forecast_webhook"),
    path(
        "api/webhooks/observations/",
        views.observations_webhook,
        name="observation_webhook",
    ),
    path("api/webhooks/texts/", views.texts_webhook, name="texts_webhook"),
    path(
        "api/webhooks/pseudoradar/",
        views.pseudoradar_webhook,
        name="pseudoradar_webhook",
    ),
    path("api/webhooks/models/", views.models_webhook, name="models_webhook"),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

tinia_manager/users/urls.py
from django.urls import path

from tinia_manager.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

tinia_manager/tinia/views.py
import base64
import datetime
import json
import math
import tempfile
import time
import zipfile

import jsonschema
import netCDF4
import requests
from django.db.models import Count
from django.db.transaction import on_commit
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, View
from django_filters import rest_framework as filters
from rest_framework.decorators import api_view, permission_classes
from rest_framework.pagination import PageNumberPagination
from rest_framework.permissions import SAFE_METHODS, BasePermission
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet
from rest_framework_api_key.permissions import HasAPIKey

from config.settings.base import env
from tinia_manager.tinia import tasks
from tinia_manager.tinia.models import (
    CurrentData,
    CurrentTexts,
    Data,
    DataBulletin,
    DataType,
    PseudoRadarBulletin,
    SkyCondition,
    Text,
    TextBulletin,
    TimeLayout,
    Venue,
    VenueType,
    Webcam,
)
from tinia_manager.tinia.serializers import (
    CurrentDataViewSerializer,
    CurrentTextsViewSerializer,
    DataBulletinSerializer,
    DataSerializer,
    DataTypeSerializer,
    PseudoRadarBulletinSerializer,
    SkyConditionSerializer,
    TimeLayoutSerializer,
    VenueSerializer,
    VenueTypeSerializer,
    WebcamSerializerDynamic,
)
from tinia_manager.users.models import User

date_format = "%Y-%m-%dT%H:%M:%S"
date_format_human = "%A, %d-%m-%Y, %H:%M, %Z"

current_tz = timezone.get_current_timezone()


def get_today_midnight():
    return datetime.datetime.combine(datetime.date.today(), datetime.time.min, datetime.timezone.utc)


def format_timestamp(value):
    return timezone.make_naive(value, current_tz).strftime(date_format)


def format_timestamp_human(value):
    return value.astimezone(current_tz).strftime(date_format_human)


def format_timestamp_human_utc(value):
    return value.astimezone(timezone.utc).strftime(date_format_human)


class AboutPageView(TemplateView):
    template_name = "pages/about.html"

    def get(self, request):
        return render(
            request,
            "pages/about.html",
        )


class IndexPageView(TemplateView):
    template_name = "pages/bulletin_texts.html"

    def get(self, request):
        if not request.user.is_authenticated:
            current_url = request.get_full_path()
            return HttpResponseRedirect(reverse("account_login") + "?next=" + current_url)
        else:
            return render(request, "pages/bulletin_texts.html")


def home(request):
    # number of each page for pagination
    num = 10

    if not request.user.is_authenticated:
        current_url = request.get_full_path()
        return HttpResponseRedirect(reverse("account_login") + "?next=" + current_url)
    else:
        # get sort data from frontend
        month = request.GET.get("month")
        year = request.GET.get("year")
        page = int(request.GET.get("page"))
        sort_col = request.GET.get("sortCol")
        sort_asc = request.GET.get("sortAsc")
        is_data_page = request.GET.get("isDataPage")
        is_draft = request.GET.get("isDraft")
        region = request.GET.get("region")

        # filter by month, year, region, is_draft
        # check bulletin for data
        if is_data_page == "1":
            bulletins = DataBulletin.objects.all()
        else:
            bulletins = TextBulletin.objects.all()
        if year:
            bulletins = bulletins.filter(last_update__year=year)
        if month != "All":
            bulletins = bulletins.filter(last_update__month=month)
        if region != "All":
            bulletins = bulletins.filter(id_venue__name_eng=region)

        if is_draft != "All":
            bulletins = bulletins.filter(draft=(is_draft == "true"))

        # get total page number
        if int(bulletins.count() / num) == (bulletins.count() / num):
            total_pages = int(bulletins.count() / num)
        else:
            total_pages = int(bulletins.count() / num) + 1
        if sort_col == "null":
            sort_col = "-last_update"
        else:
            if sort_asc == "true":
                sort_col = "-" + sort_col

        if sort_col != "data_num" and sort_col != "-data_num":
            bulletins = bulletins.order_by(sort_col)[num * (page - 1) : num * page]
        else:
            if sort_asc == "false":
                bulletins = bulletins.annotate(count=Count("datas__id")).order_by("count")[
                    num * (page - 1) : num * page
                ]
            else:
                bulletins = bulletins.annotate(count=Count("datas__id")).order_by("-count")[
                    num * (page - 1) : num * page
                ]

        editable_statuses = []
        for requested_bulletin in bulletins:
            regioncheck = 0
            if requested_bulletin.id_venue in request.user.region.all():
                regioncheck = 1
            if request.user.is_superuser or requested_bulletin.draft and regioncheck == 1:
                editable_status = 1
            else:
                editable_status = 0
            editable_statuses.append(editable_status)
        bulletins = list(bulletins.values())

        for i, bulletin in enumerate(bulletins):
            bulletin["editable_status"] = editable_statuses[i]
            bulletin["region"] = Venue.objects.get(id=bulletin["id_venue_id"]).name_eng
            bulletin["start_human"] = format_timestamp_human(bulletin["start"])
            bulletin["start_human_utc"] = format_timestamp_human_utc(bulletin["start"])
            bulletin["end_human"] = format_timestamp_human(bulletin["end"])
            bulletin["end_human_utc"] = format_timestamp_human_utc(bulletin["end"])
            bulletin["last_update_human"] = format_timestamp_human(bulletin["last_update"])
            bulletin["last_update_human_utc"] = format_timestamp_human_utc(bulletin["last_update"])
            if is_data_page == "1":
                bulletin["data_num"] = Data.objects.filter(id_data_bulletin=bulletin["id"]).count()
                bulletin["number_eng"] = 0
                bulletin["number_deu"] = 0
                bulletin["number_ita"] = 0
                bulletin["number_lld"] = 0
            else:
                bulletin_texts = TextBulletin.objects.get(id=bulletin["id"]).texts
                bulletin_one_day_texts = (
                    bulletin_texts.filter(id_time_layout=TimeLayout.get_start_day())
                    | bulletin_texts.filter(id_time_layout=TimeLayout.get_second_day())
                    | bulletin_texts.filter(id_time_layout=TimeLayout.get_third_day())
                    | bulletin_texts.filter(id_time_layout=TimeLayout.get_fourth_day())
                    | bulletin_texts.filter(id_time_layout=TimeLayout.get_fifth_day())
                    | bulletin_texts.filter(id_time_layout=TimeLayout.get_last_day())
                    | bulletin_texts.filter(id_time_layout=TimeLayout.get_mountain_day())
                )
                number_eng = number_deu = number_ita = number_lld = 0
                for bulletin_one_day_text in bulletin_one_day_texts:
                    if bulletin_one_day_text.value_eng != "":
                        number_eng += 1
                    if bulletin_one_day_text.value_deu != "":
                        number_deu += 1
                    if bulletin_one_day_text.value_ita != "":
                        number_ita += 1
                    if bulletin_one_day_text.value_lld != "":
                        number_lld += 1
                bulletin["number_eng"] = number_eng
                bulletin["number_deu"] = number_deu
                bulletin["number_ita"] = number_ita
                bulletin["number_lld"] = number_lld
                bulletin["data_num"] = 0

        regions = []
        for item in request.user.region.all():
            region = {"id": item.id, "name": item.name_eng}
            regions.append(region)

        main_regions = ["Euregio", "Tyrol", "South Tyrol", "Trentino"]
        active_ids = []
        for main_region in main_regions:
            active_bulletin = (
                TextBulletin.objects.filter(id_venue__name_eng=main_region, draft=False)
                .annotate(texts_count=Count("texts"))
                .filter(texts_count__gt=0)
                .order_by("-start", "-last_update")
            )
            if active_bulletin:
                active_ids.append(active_bulletin.first().id)
        lastupdate_ids = []
        td = datetime.datetime.combine(datetime.date.today(), datetime.datetime.min.time())
        for main_region in main_regions:
            last_edit = TextBulletin.objects.filter(
                id_venue__name_eng=main_region, draft=True, start__date=td.date()
            ).order_by("-last_update")
            if last_edit:
                lastupdate_ids.append(last_edit.first().id)
        data = {
            "bulletins": bulletins,
            "regions": regions,
            "totalpages": total_pages,
            "active_ids": active_ids,
            "lastupdate_ids": lastupdate_ids,
        }
    return JsonResponse(data, safe=False)


def bulletinTextCreateTimelayoutReturn(time_layout, day_offset):
    time_layout_mountain = TimeLayout.get_mountain_day()
    if time_layout_mountain.id == time_layout:
        return time_layout_mountain.id
    else:
        time_layout_first = TimeLayout.get_start_day()
        time_layout_second = TimeLayout.get_second_day()
        time_layout_third = TimeLayout.get_third_day()
        time_layout_fourth = TimeLayout.get_fourth_day()
        time_layout_fifth = TimeLayout.get_fifth_day()

tinia_manager/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

tinia_manager/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name", "region"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("bulletin_texts")


user_redirect_view = UserRedirectView.as_view()

tinia_manager/templates/base.html
{% load static i18n %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}meteo.report Manager{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Back-office for the Euregio Weather Report public-facing website">
    <meta name="author" content="simevo s.r.l.">

    <link rel="icon" href="/favicon.ico">
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/bootstrap-icons.css' %}" referrerpolicy="no-referrer" />

    <!-- Your stuff: Third-party CSS libraries go here -->
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      <!-- Bootstrap JS -->
      <script defer src="{% static 'js/bootstrap.min.js' %}" referrerpolicy="no-referrer"></script>
      <!-- Your stuff: Third-party javascript libraries go here -->
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script defer src="{% static 'js/alpine.js' %}"></script>

      <!-- place project specific Javascript in this file -->
      <script defer src="{% static 'js/project.js' %}"></script>

    {% endblock javascript %}

  </head>

  <body>
    <div style="min-height: 100vh; display: grid; grid-template-rows: auto 1fr auto; background-color: #F8F9FA;">
    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-dark" style="background-color: #2941A4;">
        <div class="container-fluid">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand" href="{% url 'bulletin_texts' %}" title="Bulletins">
            <img src="{% static 'images/logo-tinia-M-inverted.png' %}" alt="T" width="30" height="30">
          </a>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'bulletin_texts' %}" title="Bulletins with weather texts attached">Textual Bulletins <span class="visually-hidden">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'bulletin_data' %}" title="Bulletins with weather data attached">Data Bulletins <span class="visually-hidden">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'bulletin_pseudoradar' %}" title="Bulletins with NetCDF file attached">Pseudoradar Bulletins <span class="visually-hidden">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'dashboard' %}" title="Currently valid weather texts from today onwards">Dashboard</a>
              </li>
              {% if request.user.is_superuser %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'user_region' %}" title="Manage user-regions associations">
                  Users
                  <i class="bi bi-lock-fill"></i>
                </a>
              </li>
              <li class="nav-item ">
                <a class="nav-link" href="/{{ ADMIN_URL }}" title="Django Administration">
                  Admin
                  <i class="bi bi-lock-fill"></i>
                </a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}" title="About meteo.report Manager">About</a>
              </li>
            </ul>
            <div class="me-2 navbar-nav mr-auto">
              {% if request.user.is_authenticated %}
              <div class="d-flex flex-column">
                <div class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <div class="nav-link" style="padding: 0; color: #9ebdbd;">Welcome, <a href="{% url 'users:detail' request.user.username  %}" style="color: #dddddd;">{{ request.user.username }}</a></div>
                </div>
                <div class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <div class="nav-link" style="padding: 0; color: #9ebdbd;">Bulletins | <a href="{% url 'account_logout' %}" style="color: #dddddd;">Logout</a></div>
                </div>
              </div>
              {% else %}
                <div class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
                </div>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>

    </div>

    <div class="container-fluid">

      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->
    <footer class="text-center text-lg-start text-muted" style="bottom: 0; width: 100%;">
      <!-- Copyright -->
      <div class="text-center p-3" style="background-color: #2941A4;">
        Copyright (C) 2022-2024 <a href="https://simevo.com" target="_blank">simevo s.r.l.</a> for <a href="https://www.europaregion.info" target="_blank">Europaregion Tirol/Südtirol/Trentino</a> - Source code: <a href="https://gitlab.com/tinia-euregio/tinia-manager" target="_blank">tinia-manager</a>, AGPL-3.0-or-later
      </div>
      <!-- Copyright -->
    </footer>
    </div>

    {% block modal %}{% endblock modal %}

    {% block inline_javascript %}
    {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {/* Run whatever you want */});
    </script>
    {% endcomment %}
    {% endblock inline_javascript %}
  </body>
</html>